# Python Workshop - Exercises

## Termin 2: Datenanalyse mit Python - Numpy & Pandas
#### Torben Abts & Jonas Hummel (CorrelAid), 21.Juni 2022

In [1]:
# Install Numpy and Pandas in the current Jupyter kernel
#import sys
#!{sys.executable} -m pip install numpy
#!{sys.executable} -m pip install pandas

# Import Numpy and Pandas
import numpy as np
import pandas as pd

Die unten aufgelisteten Übungsaufgaben sollen euch dabei helfen, das soeben Gelernte besser zu verstehen und praktisch anwenden zu können. Um das Ganze etwas anschaulicher zu machen, wird die Aufgabe darin bestehen, die Mitarbeiter der Capitol-Versicherung "zu erstellen" und ihnen die passenden Attribute zuzuweisen (wem die Capitol nichts sagt, sollte vielleicht einmal Stromberg googlen ;) ).

### Aufgabenblock 1

#### Aufgabe 1.1:
Entscheide, ob die folgenden Werte in ein Array passen würden:
- 1) "Stromberg", 50000, "m", "Leiter M-Z"
- 2) 12000, 14.5, 2009, 3700.8
- 3) Reihe 1: "Stromberg", "Steinke", "Schirmann" ; Reihe 2: "Bernd", "Tanja"

Antwort:
- 1) Nein, da verschiedene Datentypen
- 2) Ja, aber ints werden zu floats umgewandelt (passiert automatisch)
- 3) Nein, da verschieden große Reihen

#### Aufgabe 1.2:
Erstelle jeweils einen eindimensionales Array mit den Vornamen und eines mit den Nachnamen der folgenden Mitarbeiter:
- Bernd Stromberg
- Erni Heisterkamp
- Ulf Steinke
- Tanja Seifert
- Jennifer Schirmann

Achte darauf, die Reihenfolge nicht zu verändern. Benenne die Arrays mit *vornamen* und *nachnamen*. Lass dir anschließend beide Arrays ausgeben. Überprüfe, ob es sich auch wirklich um Arrays handelt.

In [2]:
vornamen = np.array(["Bernd", "Erni", "Ulf", "Tanja", "Jennifer"])
nachnamen = np.array(["Stromberg", "Heisterkamp", "Steinke", "Seifert", "Schirmann"])

print(vornamen)
print(nachnamen)

print(type(vornamen), type(nachnamen))

['Bernd' 'Erni' 'Ulf' 'Tanja' 'Jennifer']
['Stromberg' 'Heisterkamp' 'Steinke' 'Seifert' 'Schirmann']
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


#### Aufgabe 1.3:
Füge nun die beiden oben erstellten Arrays zu einer Matrix zusammen. Dabei soll jeder Vorname über dem Nachnamen der Person stehen. Speichere diese Matrix unter dem Namen *vn_namen*. 

Initialisiere außerdem zwei weitere Arrays. Diese sollten integer und keine floats (default) enthalten:
- Einen Array mit dem Namen *gehalt*. Dabei soll der erste Mitarbeiter 50.000 Euro erhalten und jeder folgende Mitarbeiter 5.000 Euro weniger. Nutze hierzu eine möglichst effiziente Funktion.
- Einen Array mit dem Namen *bonus*. Erstelle den Array so, dass für jeden Mitarbeiter 0 als Platzhalter zu sehen ist.

Lass dir anschließend alle drei erstellten Array ausgeben.

In [3]:
vn_namen = np.array([vornamen, nachnamen])

gehalt = np.arange(50000, 29999, -5000, dtype=int)
bonus = np.zeros(5, dtype=int)

print(vn_namen)
print(gehalt)
print(bonus)

[['Bernd' 'Erni' 'Ulf' 'Tanja' 'Jennifer']
 ['Stromberg' 'Heisterkamp' 'Steinke' 'Seifert' 'Schirmann']]
[50000 45000 40000 35000 30000]
[0 0 0 0 0]


#### Aufgabe 1.4:

Das oben angegebene Gehalt ist in Euro angegeben. Erstelle nun ein neues Array mit dem Namen *gehalt_d*, das das Gehalt in Dollar umgerechnet angibt. Lass dir die Standardabweichung für das Gehalt in Euro und in Dollar ausgeben und vergleiche die beiden Werte (runde beide Werte auf zwei Nachkommastellen).

Erhöhe außerdem den Bonus für jeden Angestellten auf 1000 Euro. Speichere die Erhöhung in derselben Variable *bonus*.
Lass dir anschließend beide Arrays ausgeben.

In [4]:
gehalt_d = gehalt * 1.07 # Wechselkurs zum Zeitpunkt der Notebook-Erstellung
bonus = bonus + 1000

print(f"SD Gehalt in Euro {gehalt.std().round(2)}, SD Gehalt in USD {gehalt_d.std().round(2)}")

print(gehalt_d)
print(bonus)

SD Gehalt in Euro 7071.07, SD Gehalt in USD 7566.04
[53500. 48150. 42800. 37450. 32100.]
[1000 1000 1000 1000 1000]


### Aufgabenblock 2

#### Aufgabe 2.1: 

Ändere den Namen "Erni" zu "Berthold". Tue dies der Vollständigkeit halber sowohl in *vornamen* als auch in *vn_namen*. 

Lasse dir zur Kontrolle beide Arrays ausgeben.

In [5]:
vornamen[1] = "Berthold"
vn_namen[0, 1] = "Berthold"

print(vornamen)
print(vn_namen)

['Bernd' 'Berthold' 'Ulf' 'Tanja' 'Jennifer']
[['Bernd' 'Berthold' 'Ulf' 'Tanja' 'Jennifer']
 ['Stromberg' 'Heisterkamp' 'Steinke' 'Seifert' 'Schirmann']]


#### Aufgabe 2.2:

Wie oben zu sehen ist, werden in *vn_namen* erst alle Vornamen, dann alle Nachnamen in je einer Reihe ausgegeben. Das ist zwar richtig, aber für unsere Zwecke schwer lesbar. Erstelle eine Variable *vn_namen_switch*, bei der eine Reihe mit Vornamen und anschließend eine Reihe mit Nachnamen abgebildet wird. Lass dir die Variable anschließend ausgeben.

In [6]:
vn_namen_switch = vn_namen.T
print(vn_namen_switch)

[['Bernd' 'Stromberg']
 ['Berthold' 'Heisterkamp']
 ['Ulf' 'Steinke']
 ['Tanja' 'Seifert']
 ['Jennifer' 'Schirmann']]


##### Aufgabe 2.3: 

Füge die Arrays *gehalt* und *bonus* zu einer gemeinsamen Matrix *gehalt_bonus* zusammen. Erhöhe anschließend jeden der Werte in dieser Matrix mit Hilfe einer selbst geschriebenen Funktion *gehaltserhöhung* um 20%. Speichere das Ergebnis unter *gehalt_bonus_erhöht* und lasse dir die Variable ausgeben.

In [7]:
gehalt_bonus = np.row_stack((gehalt, bonus))

def gehaltserhöhung(x):
    for i in range(0, len(x)):
        x[i] = x[i] * 1.2
    return x

gehalt_bonus_erhöht = np.apply_along_axis(gehaltserhöhung, axis= 0, arr=gehalt_bonus)
gehalt_bonus_erhöht

array([[60000, 54000, 48000, 42000, 36000],
       [ 1200,  1200,  1200,  1200,  1200]])

#### Aufgabe 2.4:

Splitte nun die eben erstellten Arrays wieder zu ihren ursprünglichen eindimensionalen Array *gehalt* und *bonus* zurück und speichere sie unter den entsprechenden Variablennamen. Da beide Variablen vorher in einer Matrix vorhanden waren, haben beide nun noch eine doppelte Klammerstruktur. Entferne diese, sodass du am Ende wieder normale eindimensionale Arrays erhälst. Lass dir beide Variablen anschließend ausgeben.

In [8]:
[gehalt, bonus] = np.vsplit(gehalt_bonus_erhöht, 2)

gehalt = gehalt[0]
bonus = bonus[0]

print(gehalt)
print(bonus)

[60000 54000 48000 42000 36000]
[1200 1200 1200 1200 1200]


#### Aufgabe 2.5:

**Für alle:** Führt bitte das nächste Feld aus um sicherzustellen, dass wir an diesem Punkt alle dieselben Werte in unseren Arrays haben (durch vielfaches oder fehlerhaftes Ausführen einer Funktion kann es zu verschiedenen Werten kommen).

**Für Schnelle:** Probiert doch schon einmal, die vier hier abgebildeten Arrays zum DataFrame *mitarbeiter_df* zusammenzusetzen. Dabei sollen die Spalten die Namen "Vorname", "Nachname", "Gehalt" und "Bonus" haben. Die richtige Benennung der Spalten ist dabei wichtig für weitere Aufgaben. Lasst euch den DataFrame ausgeben (und probiert das am besten einmal mit und einmal ohne *print*-Befehl).

In [9]:
# !!! Bitte unbedingt ausführen !!!

vornamen = np.array(['Bernd', 'Berthold', 'Ulf', 'Tanja', 'Jennifer'])
nachnamen = np.array(['Stromberg', 'Heisterkamp', 'Steinke', 'Seifert', 'Schirmann'])
gehalt = np.array([60000, 54000, 48000, 42000, 36000])
bonus = np.array([1200, 1200, 1200, 1200, 1200])

In [10]:
# Für Schnelle

spalten_namen = ["Vorname", "Nachname", "Gehalt", "Bonus"]
daten = np.array([vornamen, nachnamen, gehalt, bonus]).T

mitarbeiter_df = pd.DataFrame(daten, columns=spalten_namen)
mitarbeiter_df

Vorname     Nachname Gehalt Bonus
0     Bernd    Stromberg  60000  1200
1  Berthold  Heisterkamp  54000  1200
2       Ulf      Steinke  48000  1200
3     Tanja      Seifert  42000  1200
4  Jennifer    Schirmann  36000  1200

### Aufgabenblock 3

#### Aufgabe 3.1:

Lest den Datensatz "Weitere_Mitarbeiter_Capitol" ein und speichert ihn unter dem namen *w_mitarbeiter_df*. Falls ihr bei bei Aufgabe 2.5 keinen (oder keinen funktionierenden) Datensatz für die bisher betrachteten Mitarbeiter der Capitol erstellt habt, lest außerdem den Datensatz "Mitarbeiter_Capitol" ein und speichert ihn unter dem Namen *mitarbeiter_df*. 

In [11]:
w_mitarbeiter_df = pd.read_excel("Weitere_Mitarbeiter_Capitol.xlsx")
w_mitarbeiter_df

Vorname   Nachname  Gehalt  Bonus
0         Erika   Burstedt   35000   1200
1       Tatjana     Berkel  100000   5000
2          Timo     Becker   80000   2500
3   Hans-Jürgen   Wehmeyer   80000   4000
4         Sinan    Turculu   60000   4000
5        Sabine     Buhrer   40000   1500
6          Lars   Lehnhoff   35000   1200
7        Nicole    Rückert   33000   1200
8          Maja     Decker   25000    600
9         Jonas    Fischer   18000    300
10        Achim    Dörfler   25000    500
11    Magdalena  Prellwitz   20000    300

In [12]:
mitarbeiter_df = pd.read_excel("Mitarbeiter_Capitol.xlsx")
mitarbeiter_df

Vorname     Nachname  Gehalt  Bonus
0     Bernd    Stromberg   60000   1200
1  Berthold  Heisterkamp   54000   1200
2       Ulf      Steinke   48000   1200
3     Tanja      Seifert   42000   1200
4  Jennifer    Schirmann   36000   1200

### Aufgabenblock 4